config/routes.rb
SeePeeps::Application.routes.draw do

  root to: "welcome#home"
  # Authentication routes
  get "/auth/:provider/callback",   to: "sessions#create"
  post "/auth/:provider/callback",  to: "sessions#create"
  get "/signout",                   to: "sessions#destroy", as: :sign_out

  # Search routes
  post'/search/:service',          to: 'posts#search',           as: :search

  post '/rss',                     to: 'posts#fetch_rss',        as: :rss

  delete 'unsubscribe/:id',        to: 'authors#unsubscribe',    as: :unsubscribe
  post '/tweet',                   to: 'posts#tweet',            as: :tweet
  post '/favorite',                to: 'posts#favorite',         as: :favorite
  post '/retweet',                 to: 'posts#retweet',          as: :retweet
  post '/tumblr',                  to: 'posts#post_to_tumblr',   as: :tumblr

  resources :posts
  resources :users
  resources :authors
  resources :user_authors
 end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  
  has_many :providers
  has_many :authors, through: :user_authors, uniq: true
  has_many :user_authors

  def self.create_from_omniauth(auth_hash)
    self.create!(      
      username: auth_hash["info"]["nickname"],
    )
    rescue ActiveRecord::RecordInvalid
    nil
  end

  def posts
    @posts = []
    self.authors.each do |author|
      author.posts.each do |post|
        @posts << post
      end
    end
    @posts
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :home_feed
  before_action :update_feeds

  def show
    @user = User.find(params[:id])
    if current_user
      if current_user.id == @user.id
        @providers = current_user.providers #this is just for debug, can delete later
        @posts = @updates + @home_feed
        @posts = @posts.uniq {|p| p[:body]}
        @posts.sort!{|a, b| b[:posted_at]<=> a[:posted_at]}
        @posts = @posts.paginate(:page => params[:page], :per_page => 25)
      else
        flash[:notice] = "You are not authorized to view this page!"
        redirect_to user_path(current_user)
      end
    else 
      flash[:notice] = "You must be signed in to view this page!"
      redirect_to root_path
    end
  end

  private

  def home_feed
    if current_user
      types = current_user.providers.map {|p| p.name}
      if types.include? "twitter"
        user_client = TwitterAuthor.user_client(current_user)
        @home_feed = []
        user_client.home_timeline.take(25).each do |t|
          p = {}
          p[:author_name] = t.user.screen_name
          p[:body] = t.text
          p[:posted_at] = t.created_at
          p[:author_url] = t.user.profile_image_url.to_s.gsub('normal', 'reasonably_small')
          p[:author_type] = "TwitterAuthor"
          p[:pid] = t.id
          @home_feed << p
        end
      else 
        @home_feed = []
      end
    else
      flash[:notice] = "You must be signed in to view this page!"
    end
  end

  def update_feeds 
    authors = current_user.authors
    if authors.empty?
      @updates = []
    else
      @updates = []
      authors.each do |author|
        if author.type == "InstagramAuthor"
          InstagramAuthor.client.user_recent_media(author.uid).each do |photo|
            post = {author_name:author.username, author_url: author.avatar, author_type: author.type}
            if photo.caption 
              caption = photo.caption.text
            else
              caption = ""
            end
            post[:body] = "<img src= '#{photo.images.standard_resolution.url}', width='450'>"
            post[:posted_at] = Time.at(photo.created_time.to_i)
            post[:caption] = "<span class='instagram_caption'>#{caption}</span>"
            @updates << post
          end
        elsif author.type == "TwitterAuthor"
          TwitterAuthor.client.user_timeline(author.username).collect.each do |tweet|
            post = {author_name:author.username, author_url: author.avatar, author_type: author.type}
            post[:body] = tweet.text 
            post[:posted_at] = tweet.created_at
            post[:pid] = tweet.id
            @updates << post
          end
        elsif author.type == "TumblrAuthor"
          posts = TumblrAuthor.client.posts(author.username)["posts"]
          posts.each do |t|
            @updates << tumblr_hash(t,author)        
          end
        elsif author.type == "RssAuthor"
          feed = Feedzirra::Feed.fetch_and_parse(author.uid)
          Feedzirra::Feed.update(feed).entries.each do |entry|
            post = {author_name: author.username, author_url: author.avatar, author_type: author.type}
            post[:body] = "<a href='" + entry.url + "''>" + entry.title + "</a><br>" + entry.summary
            post[:caption] = entry.title
            post[:posted_at] = entry.published
            @updates << post
          end
        else 
          @updates = []
        end
      end
    end
  end

  private

  def tumblr_hash(t, author)
    post = {  author_name:author.username, 
              author_url: author.avatar, 
              author_type: author.type,
              posted_at: t['date'].to_time
            }
    if t['type']    == 'text'
      post[:body]   = t["body"]
    elsif t['type'] == 'video'
      post[:body]   = t["player"].first["embed_code"]
    elsif t['type'] == 'audio'
      post[:body] = t["player"]
    elsif t['type'] == 'chat'
      chat = t['body'].gsub(/\r\n/, '<br>')
      post[:body] = chat
    elsif t['type'] == 'quote'
      post[:body] = '<h4>' + t["text"] + '</h4>' + '<br>' + '<em>' + '--' + t["source"] + '<em>'
    elsif t['type'] == 'photo'
      photoset = t['photos'].map {|photo| "<img src= '#{photo['original_size']['url']}', width= '450'>"}.join("")
      post[:body] = photoset
    elsif t['type'] == 'link'
      post[:body] = '<a href="' + t['url'] + '">' + t['title'] + '</a>'
    elsif t['type'] == 'answer'
      post[:body] = t['question'] + t['answer']
      
    end
    post

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div id="content">
  <nav id="profiletabs">
    <ul>
      <li><a href="#feed" class="sel">My Feed</a></li>
      <li><a href="#subs">My Subscriptions</a></li>
      <li><a href="#account">My Account</a></li>
    </ul>
  </nav>

  <section id="feed">
    <div class='container'><br>
      <% if @posts.empty? %>
        <h3>Your feed is empty. Add some peeps!</h3>
      <% else %>
        <h3>What your peeps are saying:</h3>
        <% @posts.each do |p| %>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-1" align="right" height="80px" >
              <%= image_tag "#{p[:author_type].partition(/Author/).first.downcase}.png" %>
            </div>
            <div class="col-md-1">
              <div class="avatar">
                
                <%= img_linkify(p) %>
              </div>
            </div>
            <div class="col-md-7">
              <div class="text">
                <div class="author"><%= txt_linkify(p) %></div>
                <p><%= render_post(p) %><br>
                  <% if p[:author_type] == "TwitterAuthor" && has_twitter_provider %>
                    <p>
                      <%= link_to "Favorite", favorite_path(tweet: p), method: :post %> |
                      <%= link_to "Retweet", retweet_path(tweet: p), method: :post %>
                    </p>
                  <% end %>
                 <span class='timestamp'>
                  Posted at <%= p[:posted_at].strftime("%l:%M %p on %A, %b %e, %Y") %>
                </span></p>
              </div>
            </div>
          </div>
          <br>
        <% end %>
        <div class="text-center"><%= will_paginate @posts %></div>
      <% end %>

    </div>
  </section>

  <section id="subs" class="hidden">
    <div class='container'>
      <% if current_user.authors.empty? %>
        <h3>Where are your peeps? Start following!</h3>
      <% else %>
        <h3>You are currently following:</h3>
        <% current_user.authors.each do |author| %>
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-1" align="right" height="80px">
            <%= image_tag "#{author.type.partition(/Author/).first.downcase}.png" %>
          </div>
          <div class="col-md-1">
            <div class="avatar">
              <%= auth_img_linkify(author) %>
            </div>
          </div>
          <div class="col-md-7">
            <div class="text">
              <div class="author"><%= auth_txt_linkify(author)%></div>
              <%= button_to "Unsubscribe", unsubscribe_path(author: author), method: :delete, type: "submit", class: "btn btn-info" %>
            </div>
          </div>
        </div>
        <br>
        <% end %>
      <% end %>
    </div>
  </section>

  <section id="account" class="hidden">
    <div class='link_accounts'>
      <h4>Your accounts</h4>
      <ul>
        <% @providers.each do |p| %>
          <%= image_tag "#{p.name}.png" %>
          <%= image_tag("#{p['avatar_url']}", height: '50') %>
          <%= p['username'] %><br>

        <% end %>
      </ul>
      <h4>Link another account</h4>
      <div class="icons">
        <%= link_to (image_tag "twitter.png"), "/auth/twitter", title: "Twitter"%>
        <%= link_to (image_tag "tumblr.png"), "/auth/tumblr", title: "Tumblr" %>
        <%= link_to (image_tag "instagram.png"), "/auth/instagram", title: "Instagram" %>
      </div>
    </div>
  </section>
</div>