config/routes.rb
SeePeeps::Application.routes.draw do

  root to: "welcome#home"
  # Authentication routes
  get "/auth/:provider/callback",   to: "sessions#create"
  post "/auth/:provider/callback",  to: "sessions#create"
  get "/signout",                   to: "sessions#destroy", as: :sign_out

  # Search routes
  post'/search/:service',          to: 'posts#search',           as: :search

  post '/rss',                     to: 'posts#fetch_rss',        as: :rss

  delete 'unsubscribe/:id',        to: 'authors#unsubscribe',    as: :unsubscribe
  post '/tweet',                   to: 'posts#tweet',            as: :tweet
  post '/favorite',                to: 'posts#favorite',         as: :favorite
  post '/retweet',                 to: 'posts#retweet',          as: :retweet
  post '/tumblr',                  to: 'posts#post_to_tumblr',   as: :tumblr

  resources :posts
  resources :users
  resources :authors
  resources :user_authors
 end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :body, presence: :true
  belongs_to :author
  attr_accessor :feed

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_twitter_client, only:[:tweet, :favorite, :retweet]
  before_action :set_tumblr_client, only:[:post_to_tumblr]

  def search
    if params[:service] == "instagram"
      @results = InstagramAuthor.client.user_search(params[:instagram])
      render :instagram_results #all the renders should be refactored to one search page
    elsif params[:service] == "tumblr"
      @results = TumblrAuthor.client.posts(params[:search_tum])
      if @results == {"status"=>404, "msg"=>"Not Found"}
        redirect_to user_path(current_user), notice: "No users match your search."
      else
        flash[:notice] = "Search results for \"#{params[:search_tum]}\""
        render :search_tum # see above
      end
    elsif params[:service] == "twitter"
      @results = TwitterAuthor.client.user_search(params[:twitter_search]).collect
      flash[:notice] = "Search results for \"#{params[:twitter_search]}\""
      render :twitter_search #see above
    elsif params[:service] == "github"
      @results = []
      results = GithubAuthor.client.search_users(params[:github_search])
      results.items.each do |item|
        user = item.rels[:self].get.data
        httparty_response = HTTParty.get("https://api.github.com/users/#{user.login}", :headers => {"User-Agent" => "rss-peep"})
        user = {
          avatar:   httparty_response["avatar_url"],
          id:       user.id,
          username: user.login,
          link:     httparty_response["html_url"]
        }
        @results << user
      end
      flash[:notice] = "Search results for \"#{params[:github_search]}\""
      render :github_search_results
    end
  end

  def fetch_rss
    url = params[:get_rss]
    feed = Feedzirra::Feed.fetch_and_parse(url)
    feed = nil if feed.is_a?(Fixnum)

    if feed
      # get an icon from Feedzirra somehow?
      @author = current_user.authors.create(
        username: feed.title, #url.match(/http:\/\/www.\w+\.\w+/).to_s, 
        uid: url, 
        type: "RssAuthor", 
        avatar: "")
      flash[:notice] = "Feed successfully added!"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "There was a problem saving your feed!"
      redirect_to user_path(current_user)
    end
  end

  def tweet
    @user_client.update(params[:tweet])
    redirect_to :back, notice: "Your tweet has been successfully posted!"
  end

  def favorite
    @user_client.favorite(params[:tweet][:pid])
    redirect_to :back, notice: "You have successfully favorited this tweet!"
  end

  def retweet
    @user_client.retweet(params[:tweet][:pid])
    redirect_to :back, notice: "You have successfully retweeted this tweet!"
  end

  def post_to_tumblr
    blogname = current_user.providers.where(name:"tumblr").first.username
    @tumblr_client.text("#{blogname}.tumblr.com", {body: params[:tumblr]})
    redirect_to user_path(current_user)
  end

  private

  def set_twitter_client
    @user_client = TwitterAuthor.user_client(current_user)
  end

  def set_tumblr_client
    @tumblr_client = TumblrAuthor.user_client(current_user)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/github_search_results.html.erb
<% @results.each do |r| %>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-1" align="right" height="80px" >
      <%= image_tag "github.png" %>
    </div>
    <div class="col-md-1">
      <!-- <div class="avatar"> -->
        <%= link_to image_tag("#{r[:avatar]}", :class=> "img-thumbnail", size: "80"), r[:link], target: "_blank" %>
      <!-- </div> -->
    </div>
    <div class="col-md-7">
      <div class="text">
        <div class="author">
          <%= link_to r[:username], r[:link], target: "_blank" %>
        </div>

       <!--  <%= button_to "Subscribe", "", class: 'btn btn-info'  %> -->
      </div>
    </div>
  </div>
<br>
<% end %>

app/views/posts/instagram_results.html.erb
<% @results.each do |r| %>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-1" align="right" height="80px" >
      <%= image_tag "instagram.png" %>
    </div>
    <div class="col-md-1">
      <%= link_to image_tag("#{r.profile_picture}", :class=> "img-thumbnail", size: "80"), "http://instagram.com/#{r.username}", target: "_blank" %>
    </div>
    <div class="col-md-7">
      <div class="author">
        <%= link_to r.username, "http://instagram.com/#{r.username}", target: "_blank" %>
      </div>
      <%= button_to "Subscribe", authors_path(author: create_instagram_author(r)), class: 'btn btn-info' %>
    </div>
  </div>
<br>
<% end %>

app/views/posts/search_tum.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-1" align="right" height="80px" >
    <%= image_tag "tumblr.png" %>
  </div>
  <div class="col-md-1">
    <!-- <div class="avatar"> -->
    <%= link_to image_tag("http://api.tumblr.com/v2/blog/#{@results["blog"]["name"]}.tumblr.com/avatar/512", :class=> "img-thumbnail", :size=> "80x80"), "http://#{@results["blog"]["name"]}.tumblr.com", target: "_blank" %>
    <!-- </div> -->
  </div>
  <div class="col-md-6">
    <div class="text">
      <!-- these should probably be h3 and h4, but alignment gets off-same in twitter -->
      <span class= 'author'><%= link_to @results["blog"]["name"], "http://#{@results["blog"]["name"]}.tumblr.com", target: "_blank" %></span><br>
      <span class='tumblr_title'><%= @results["blog"]["title"] %></span>
      <p class= 'tumblr_description'><%= @results["blog"]["description"].html_safe %></p>
      <%= button_to "Subscribe!", authors_path(author: create_tum_author_hash(@results)), class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/posts/twitter_search.html.erb
<% @results.each do |r| %>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-1" align="right" height="80px" >
      <%= image_tag "twitter.png" %>
    </div>
    <div class="col-md-1">
      <!-- <div class="avatar"> -->
        <%= link_to image_tag("#{r.profile_image_url.to_s.gsub('normal', 'reasonably_small')}", :class=> "img-thumbnail", size: "80"), "https://twitter.com/#{r.screen_name}", target: "_blank" %>
      <!-- </div> -->
    </div>
    <div class="col-md-7">
      <div class="text">
        <div class="author">
          <%= link_to r.screen_name, "https://twitter.com/#{r.screen_name}", target: "_blank" %>
        </div>
        <p><%=r.description %></p>
        <%= button_to "Subscribe", authors_path(author: create_twitter_author_hash(r)), class: 'btn btn-info'  %>
      </div>
    </div>
  </div>
<br>
<% end %>

app/views/posts/twitter_search_results.html.erb
<% @search.each do |r| %>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-1" align="right" height="80px" >
      <%= image_tag "twitter.png" %>
    </div>
    <div class="col-md-1">
      <!-- <div class="avatar"> -->
        <%= link_to image_tag("#{r.profile_image_url.to_s.gsub('normal', 'reasonably_small')}", :class=> "img-thumbnail", size: "80"), "https://twitter.com/#{r.screen_name}", target: "_blank" %>
      <!-- </div> -->
    </div>
    <div class="col-md-7">
      <div class="text">
        <div class="author">
          <%= link_to r.screen_name, "https://twitter.com/#{r.screen_name}", target: "_blank" %>
        </div>
        <p><%=r.description %></p>
        <%= button_to "Subscribe", authors_path(author: create_twitter_author_hash(r)), class: 'btn btn-info'  %>
      </div>
    </div>
  </div>
<br>
<% end %>