config/routes.rb
SeePeeps::Application.routes.draw do

  root to: "welcome#home"
  # Authentication routes
  get "/auth/:provider/callback",   to: "sessions#create"
  post "/auth/:provider/callback",  to: "sessions#create"
  get "/signout",                   to: "sessions#destroy", as: :sign_out

  # Search routes
  post'/search/:service',          to: 'posts#search',           as: :search

  post '/rss',                     to: 'posts#fetch_rss',        as: :rss

  delete 'unsubscribe/:id',        to: 'authors#unsubscribe',    as: :unsubscribe
  post '/tweet',                   to: 'posts#tweet',            as: :tweet
  post '/favorite',                to: 'posts#favorite',         as: :favorite
  post '/retweet',                 to: 'posts#retweet',          as: :retweet
  post '/tumblr',                  to: 'posts#post_to_tumblr',   as: :tumblr

  resources :posts
  resources :users
  resources :authors
  resources :user_authors
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeePeeps</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>
      <% if current_user %>
        Hi, <%=link_to "#{current_user.username}!", user_path(current_user) %> |
        <%= link_to "Sign Out", sign_out_path %>
      <% end %>

      <h1><%= link_to (image_tag "PeepsYellow.png"), "" %>PEEPS</h1>
    <% if current_user %>
      <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" >Search for your Peeps:</a>
        </div>
          <ul class="nav navbar-nav">
            <li class= "dropdown">
              <a onclick="#" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="caret"></b>
                <span><%= image_tag "instagram.png", size: "20x20" %> Instagram </span>
              </a>
                <ul role="menu" class="dropdown-menu">
                 <%= form_tag search_path("instagram"), :class =>"navbar-form", method: 'post' do %>
                  <div class="form-group">
                    <%= text_field_tag "instagram", nil, placeholder: "Search Instagram", class: "input-large" %>
                  </div>
                  <button type="submit" class="btn-sm btn-info">Go!</button>
                <% end %>
                </ul>
            </li>
            <!-- Search Github -->
            <li class= "dropdown">
              <a onclick="#" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="caret"></b>
                <span><%= image_tag "github.png", size: "20x20" %> GitHub </span>
              </a>
                <ul role="menu" class="dropdown-menu">
                 <%= form_tag search_path("github"), :class =>"navbar-form", method: 'post' do %>
                  <div class="form-group">
                    <%= text_field_tag "github_search", nil, placeholder: "Search GitHub", class: "input-large" %>
                  </div>
                  <button type="submit" class="btn-sm btn-info">Go!</button>
                <% end %>
                </ul>
            </li>
            <!-- Search Tumblr -->
            <li class= "dropdown">
              <a onclick="#" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="caret"></b>
                <span><%= image_tag "tumblr.png", size: "20x20" %> Tumblr </span>
              </a>
                <ul role="menu" class="dropdown-menu">
                 <%= form_tag search_path("tumblr"), :class =>"navbar-form", method: 'post' do %>
                  <div class="form-group">
                    <%= text_field_tag "search_tum", nil, placeholder: "Search Tumblr", class: "input-large" %>
                  </div>
                  <button type="submit" class="btn-sm btn-info">Go!</button>
                <% end %>
                </ul>
            </li>
            <!-- Search Twitter -->
            <li class= "dropdown">
              <a onclick="#" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="caret"></b>
                <span><%= image_tag "twitter.png", size: "20x20" %> Twitter </span>
              </a>
              <ul role="menu"  class="dropdown-menu">
                <%= form_tag search_path("twitter"), :class =>"navbar-form", method: 'post' do %>
                  <div class="form-group">
                    <%= text_field_tag "twitter_search", nil, placeholder: "Search Twitter", class: "input-large" %>
                  </div>
                  <button type="submit" class="btn-sm btn-info">Go!</button>
                <% end %>
              </ul>
            </li>
            <!-- Add RSS -->
            <li class= "dropdown">
              <a onclick="#" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="caret"></b>
                <span><%= image_tag "rss.png", size: "20x20" %> RSS Feed </span>
              </a>
              <ul role="menu" class="dropdown-menu">
                <!-- change route to go to users controller? -->
                <%= form_tag rss_path, :class =>"navbar-form", method: 'post' do %>
                  <div class="form-group">
                    <%= text_field_tag "get_rss", nil, placeholder: "Add a feed", class: "input-large" %>
                  </div>
                  <button type="submit" class="btn-sm btn-info">Go!</button>
                <% end %>
              </ul>
            </li>
          </ul>
          <!-- posting to twitter -->
          <% if has_twitter_provider %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag "tweet.jpg", size: "20x20" %>Post to Twitter <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= form_tag(tweet_path, :class =>"navbar-form", method: 'post', type: 'text') do %>
                      <div class="form-group">
                        <%= text_field_tag :tweet, "", class: "input-large custom", placeholder: "Post to Twitter", size: "20", maxlength: "140", onkeyup: "CheckMaxlength(this);"%>
                      </div>
                      <%= submit_tag("Tweet!", class: "btn-block btn-info") %>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          <% end %>

          <!-- posting to tumblr -->
          <% if has_tumblr_provider %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag "tumblr.jpg", size: "20x20" %>Post to Tumblr <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= form_tag(tumblr_path, :class =>"navbar-form", method: 'post', type: 'text') do %>
                      <div class="form-group">
                        <%= text_field_tag :tumblr, "", class: "input-large custom", placeholder: "Post to Tumblr", size: "20", maxlength: "140", onkeyup: "CheckMaxlength(this);"%>
                      </div>
                      <%= submit_tag("Post!", class: "btn-block btn-info") %>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </nav>
    <% end %>

    <% if flash[:notice] %>
      <div class='notice'>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>